### ISSUE TITLE
Where do we write success code after logging into social networks

### ISSUE THREAD

**Issue by sciage** [multidots/android-social-signin-helper#1]
I have tried all possibilities but I cannot add code which needs to start another activity after the helper class has done a successful code. Please let me know how to go to another activity after getting successful login

**Comment by kevalpatel2106** [comment]
Each social login has its own success callback method. You can write your start activity code into that. For example, if you are using google login you can start new activity by below way:
```
  @Override
    public void onGSignInSuccess(Person person) {
        Toast.makeText(this, "Google sign in success", Toast.LENGTH_SHORT).show();
        startActivity(MainActivity.this, XYZ.class);
    }
```
