### ISSUE TITLE
Facebook Profile Image

### ISSUE THREAD

**Issue by cliffgr** [multidots/android-social-signin-helper#2]
D/Person profile pic:: {"data":{"is_silhouette":false,"url":"https:\/\/scontent.xx.fbcdn.net\/v\/t1.0-1\/p50x50\/14238173_10209572739412158_550953185722752233_n.jpg?oh=084955ed46beaffe14c682a0b25d1a66&oe=58A127F7"}}

On profile image i get that Json Object

**Comment by kevalpatel2106** [comment]
This issue is fixed in pull request #3 .
