### ISSUE TITLE
How to get keys

### ISSUE THREAD

**Issue by sanurag51** [multidots/android-social-signin-helper#8]
Thanks for such a nice project, I used this project for login with twitter, i am new in this field. how do i get the TWITTER API KEY and TWITTER SECRETE KEY which you used in TwitterHelper object

`mTwitterHelper = new TwitterHelper(R.string.twitter_api_key,
                R.string.twitter_secrate_key,
                this,
                this);`

in MainActivity.java

Also what is Fabric and what is use of it. can you please help me to learn this typical things.

thank you.

**Comment by kevalpatel2106** [comment]
You can receive this from the  https://dev.twitter.com/apps.
